server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5462/hrdb
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/erp-realm

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# بهترین روش: استفاده از environment variable ها برای password و username
# spring.datasource.password=${DB_PASSWORD:postgres}
# spring.datasource.username=${DB_USER:postgres}
